version: '3.1'

services:

  wp:
    image: wordpress:5.4.0
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - ./:/var/www/html/
    command: bash -c "/bin/chown -R www-data:www-data /var/www/html && apache2-foreground"

  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
